name: FishBroadcast
version: 2.1
main: pl.panryba.mc.broadcast.Plugin
commands:
  brc:
    permission: fish.broadcast.manage
    usage: /<command> [add <message> | remove <index> | edit <index> <new message> | list | reload | delay <new delay in seconds> | alert <period> <message> | token <name> [<value>]]
permissions:
  fish.broadcast.manage:
    description: Allows you to manage broadcast messages
    default: op
  fish.broadcast.list:
    description: Allows messages listing
    default: op
